project:
  type: book
  output-dir: docs
book:
  title: "Introducción al Lenguaje de Programación Python para Análisis Estadístico"
  subtitle: "Guía para el estudiante"
  author: 
    - Alex Bajaña
    - Brad Puglla
    - Paul Yungán
  date: "8/18/2021"
  chapters:
    - index.qmd
    - intro.qmd
    - Clase_1.qmd
    - Clase_2.qmd
format:
  html:
    number-sections: false
    theme: cosmo
number-depth: 1
