<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Introducción al Lenguaje de Programación Python para Análisis Estadístico - Análisis de correlación y modelos de regresión en Python</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./clase_7.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<meta name="mermaid-theme" content="neutral">
<script src="site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./clase_8.html"><span class="chapter-title">Análisis de correlación y modelos de regresión en Python</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introducción al Lenguaje de Programación Python para Análisis Estadístico</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Indice (en construcción)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Introducción</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Clase_1.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Introducción a Python y su entorno de desarrollo</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Clase_2.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Introducción al manejo de datos en Python con pandas</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./clase_3.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Funciones y la importancia del análisis de datos</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./clase_4.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Variables aleatorias, funciones de distribución y estimación de parametros</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./clase_6.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Exploración y visualización de datos con Matplotlib y Seaborn en Python</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./clase_7.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Pruebas de hipótesis para la media entre grupos en Python</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./clase_8.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Análisis de correlación y modelos de regresión en Python</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#teorema-de-bayes" id="toc-teorema-de-bayes" class="nav-link active" data-scroll-target="#teorema-de-bayes">Teorema de Bayes</a>
  <ul class="collapse">
  <li><a href="#conceptos-clave-de-la-regresión-lineal" id="toc-conceptos-clave-de-la-regresión-lineal" class="nav-link" data-scroll-target="#conceptos-clave-de-la-regresión-lineal">Conceptos Clave de la Regresión Lineal</a></li>
  <li><a href="#estimación-de-los-coeficientes" id="toc-estimación-de-los-coeficientes" class="nav-link" data-scroll-target="#estimación-de-los-coeficientes">Estimación de los Coeficientes</a></li>
  </ul></li>
  <li><a href="#vamos-a-ver-la-regresión-lineal-en-todo-su-poder" id="toc-vamos-a-ver-la-regresión-lineal-en-todo-su-poder" class="nav-link" data-scroll-target="#vamos-a-ver-la-regresión-lineal-en-todo-su-poder">Vamos a ver la regresión lineal en todo su poder:</a></li>
  <li><a href="#supuestos-de-la-regresión-lineal" id="toc-supuestos-de-la-regresión-lineal" class="nav-link" data-scroll-target="#supuestos-de-la-regresión-lineal">Supuestos de la regresión lineal</a></li>
  <li><a href="#la-regresión-lineal-como-una-prueba-de-diferencia-de-media" id="toc-la-regresión-lineal-como-una-prueba-de-diferencia-de-media" class="nav-link" data-scroll-target="#la-regresión-lineal-como-una-prueba-de-diferencia-de-media">La regresión lineal como una prueba de diferencia de media</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Análisis de correlación y modelos de regresión en Python</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>Para empezar nuestro análisis vamos a conversar sobre la probabilidad condicional. Con un pequeño ejemplo. Vale la pena mencionar que los ejemplos que vamos a utilizar pertenecen a un país ficticio a menos que empleemos datos reales, en cuyo caso te diremos para que cargues los datos necesarios para empezar el análisis. En ese sentido vamos a empezar con una definición de <strong>probabilidad condicional</strong> e independencia de objetos.</p>
<p>Partamos del ejemplo en la unidad 4 sobre el lanzamiento de dos dados. Cambiemos ligeramente el experimento y analicemos la probabilidad de tener la combinación <span class="math inline">\((3,5)\)</span> tras lanzar el mismo dado dos veces. Este fenómeno se puede dar de dos maneras:</p>
<p>La primera es que en el primer lanzamiento tengamos un 3 y en el segundo un 5, es decir:</p>
<p><span class="math display">\[
P(A \cap  B) = P(A) \times P(B|A)
\]</span></p>
<p>O al revés, es decir, que en el primer lanzamiento tengamos un 5 y en el segundo un 3:</p>
<p><span class="math display">\[
P(A \cap  B) = P(B) \times P(A|B)
\]</span></p>
<p>Como puedes ver lo que vemos es que para cada caso <span class="math inline">\(P(A|B)\)</span> y <span class="math inline">\(P(B|A)\)</span> es igual a <span class="math inline">\(1/6\)</span> ya que en el primer lanzamiento (<span class="math inline">\(P(A)\)</span> o <span class="math inline">\(P(B)\)</span> respectivamente) no hay algo que altere el resultado del segundo lanzamiento. En este caso decimos que los eventos son <strong>independientes</strong>. Es decir que la probabilidad de un evento no afecta la probabilidad de otro evento. En otras palabras <span class="math inline">\(P(A|B) = P(A)\)</span> o <span class="math inline">\(P(B|A) = P(B)\)</span></p>
<p>Pero veamos otro ejemplo donde podamos apreciar la probabilidad condicional. En una clase de 20 estudiantes, donde 12 son mujeres y 8 son hombres ¿Cual sería la probabilidad de que los dos primeros estudiantes en entregar el examen sean hombres?. Hagamos un diagrama de arbol para entender mejor el problema.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<div>
<pre class="mermaid mermaid-js">flowchart LR
  A[Hard edge] --&gt; B(Round edge)
  B --&gt; C{Decision}
  C --&gt; D[Result one]
  C --&gt; E[Result two]
</pre>
</div>
</div>
</div>
</div>
<section id="primero-en-entregar" class="level4">
<h4 class="anchored" data-anchor-id="primero-en-entregar">Primero en entregar</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<div>
<pre class="mermaid mermaid-js">graph LR
  
    A(Aula)
    subgraph Primero en entregar
      B("Hombre")
      C("Mujer")
    end
    

    A --&gt; B
    A --&gt; C
    
</pre>
</div>
</div>
</div>
</div>
</section>
<section id="primeras-probabilidades" class="level4">
<h4 class="anchored" data-anchor-id="primeras-probabilidades">Primeras probabilidades</h4>
<p>La clase está completa:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<div>
<pre class="mermaid mermaid-js">graph LR
  
    A(Aula)
    subgraph Primero en entregar
      B("Hombre (8/20)")
      C("Mujer (12/20)")
    end
    

    A --&gt; B
    A --&gt; C
    
</pre>
</div>
</div>
</div>
</div>
</section>
<section id="segundo-en-entregar" class="level4">
<h4 class="anchored" data-anchor-id="segundo-en-entregar">Segundo en entregar</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<div>
<pre class="mermaid mermaid-js">graph LR
  
    A(Aula)
    subgraph Primero en entregar
      B("Hombre (8/20)")
      C("Mujer (12/20)")
    end
    subgraph Segundo en entregar
      D("Hombre")
      E("Mujer")
      F("Hombre")
      G("Mujer")
    end
    

    A --&gt; B
    A --&gt; C
    B --&gt; D
    B --&gt; E
    C --&gt; F
    C --&gt; G


</pre>
</div>
</div>
</div>
</div>
</section>
<section id="segundas-probabilidades" class="level4">
<h4 class="anchored" data-anchor-id="segundas-probabilidades">Segundas probabilidades</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<div>
<pre class="mermaid mermaid-js">graph LR
  
    A(Aula)
    subgraph Primero en entregar
      B("Hombre (8/20)")
      C("Mujer (12/20)")
    end
    subgraph Segundo en entregar
      D("Hombre (7/19)")
      E("Mujer (12/19)")
      F("Hombre (8/19)")
      G("Mujer (11/19)")
    end
    

    A --&gt; B
    A --&gt; C
    B --&gt; D
    B --&gt; E
    C --&gt; F
    C --&gt; G


</pre>
</div>
</div>
</div>
</div>
<p>De izquierda a derecha vamos a seguir la historia de de este evento. En este caso, el primer estudiante en entregar la prueba será de <span class="math inline">\(8/20\)</span> hombre, mientras que la probabilidad de que el segundo estudiante sea hombre es <span class="math inline">\(7/19\)</span> ya que el primer estudiante fue hombre y ya entrego el examen.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<div>
<pre class="mermaid mermaid-js">graph LR
  
    A(Aula)
    subgraph Primero en entregar
      B("Hombre (8/20)")
      C("Mujer (12/20)")
    end
    subgraph Segundo en entregar
      D("Hombre (7/19)")
      E("Mujer (12/19)")
      F("Hombre (8/19)")
      G("Mujer (11/19)")
    end
    

    A --&gt; B
    A --&gt; C
    B --&gt; D
    B --&gt; E
    C --&gt; F
    C --&gt; G
    
    linkStyle 2 stroke:purple
    linkStyle 0 stroke:purple


</pre>
</div>
</div>
</div>
</div>
<p>Si <span class="math inline">\(A\)</span> es el evento en que el primer estudiante es hombre y <span class="math inline">\(B\)</span> es el evento en que el segundo estudiante es hombre, entonces la probabilidad de que ambos sean hombres es:</p>
<p><span class="math display">\[
P(A \cap  B) = \frac{8}{20} \times \frac{7}{19} = \frac{14}{95}
\]</span></p>
<p>En este caso la probabilidad del segundo evento está condicionada al primer evento. Es decir, la probabilidad de que el segundo estudiante sea hombre depende de que el primer estudiante sea hombre. En este caso decimos que los eventos son <strong>dependientes</strong>. Es decir que la probabilidad de un evento afecta la probabilidad de otro evento. En otras palabras <span class="math inline">\(P(A|B) \neq P(A)\)</span> o <span class="math inline">\(P(B|A) \neq P(B)\)</span>.</p>
</section>
<section id="teorema-de-bayes" class="level2">
<h2 class="anchored" data-anchor-id="teorema-de-bayes">Teorema de Bayes</h2>
<p>Hagamos un ejemplo con Python que nos ayude a visualizar de mejor manera la probabilidad condicional. Empecemos con unos datos, lo que tienes en tus manos es una muestra del 10% de la población presente en la Encuesta Nacional de Desnutrición Infantil (ENDI), trabajaremos con algunas variables:</p>
<div class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>datos <span class="op">=</span> pd.read_table(<span class="st">"data/sample_endi_10p.txt"</span>,delimiter <span class="op">=</span> <span class="st">"</span><span class="ch">\t</span><span class="st">"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>datos.columns</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="1">
<pre><code>Index(['sexo', 'etnia', 'dcronica', 'region', 'n_hijos'], dtype='object')</code></pre>
</div>
</div>
<p>Nuestro objetivo será emplear estos datos para calcular la probabilidad de encontrar en nuestra muestra un infante de sexo femenino que tenga desnutrición crónica infantil. Empecemos con una tabla rápida para calcular las proporciones adecuadas:</p>
<div class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Podemos ver los conteos:</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>pd.crosstab(datos[<span class="st">"sexo"</span>],datos[<span class="st">"dcronica"</span>])</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># E incluir los totales:</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>pd.crosstab(datos[<span class="st">"sexo"</span>],datos[<span class="st">"dcronica"</span>], margins <span class="op">=</span> <span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">dcronica</th>
<th data-quarto-table-cell-role="th">0.0</th>
<th data-quarto-table-cell-role="th">1.0</th>
<th data-quarto-table-cell-role="th">All</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">sexo</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Hombre</td>
<td>872</td>
<td>221</td>
<td>1093</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Mujer</td>
<td>906</td>
<td>195</td>
<td>1101</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">All</td>
<td>1778</td>
<td>416</td>
<td>2194</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Ahora calculemos las proporciones:</p>
<div class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fijense que no estoy usando los margenes ¿Qué pasa si los incluimos?</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>cruce <span class="op">=</span> pd.crosstab(datos[<span class="st">"sexo"</span>],datos[<span class="st">"dcronica"</span>])</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>total_global <span class="op">=</span> cruce.<span class="bu">sum</span>().<span class="bu">sum</span>()</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>proporcion <span class="op">=</span> pd.crosstab(datos[<span class="st">"sexo"</span>],datos[<span class="st">"dcronica"</span>],margins <span class="op">=</span> <span class="va">True</span>) <span class="op">/</span>total_global</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(proporcion)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>dcronica       0.0       1.0       All
sexo                                  
Hombre    0.397448  0.100729  0.498177
Mujer     0.412944  0.088879  0.501823
All       0.810392  0.189608  1.000000</code></pre>
</div>
</div>
<p>Si volvemos a nuestro ejercicio, consideramos a <span class="math inline">\(B\)</span> como el evento de que se seleccione un infante de sexo femenino, y <span class="math inline">\(A\)</span> como el evento en que el infante seleccionado tiene desnutrición crónica (valor igual a 1) tendriamos lo siguiente:</p>
<blockquote class="blockquote">
<p>Primero para el evento dado: <span class="math display">\[P(B) =  P(B \cap A) + P(B \cap A^c) = 0.412.. + 0.089.. = 0.501823\]</span> Luego vemos a que <span class="math inline">\(P(A \cap B) = 0.088879\)</span></p>
<p>Entonces la probabilidad condicional <span class="math display">\[P(A|B) = \frac{P(A \cap B)}{P(B)} = 0.177111\]</span></p>
</blockquote>
<p>Pero que tal si ahora le damos la vuelta al ejercicio ¿Cual sería la probabilidad de que habiendo elegido un niño al azar sin desnutrición crónica, este resulte ser mujer?</p>
<blockquote class="blockquote">
<p>Primero para el evento dado: <span class="math display">\[P(A) =  P(A \cap B) + P(A \cap B^c) = 0.189608\]</span> Luego vemos a que <span class="math inline">\(P(A \cap B) = 0.088879\)</span>$</p>
<p>Entonces la probabilidad condicional <span class="math display">\[P(A|B) = \frac{P(A \cap B)}{P(B)} = 0.468751\]</span></p>
</blockquote>
<p>Interesante verdad, en este caso importa de que población estamos hablando a la hora de tomar las proporciones.</p>
<p>Ahora veamos con Python como podemos hacer los cálculos de variables agrupadas en este estilo de forma adecuada, pero en este caso vamos a emplear funciones <code>lambda</code> para calcular el numero de hijos promedio en los hogares de los con y sin desnutrición infantil:</p>
<div class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>pivot_table <span class="op">=</span> pd.pivot_table(datos, values<span class="op">=</span><span class="st">'n_hijos'</span>, index<span class="op">=</span>[<span class="st">'sexo'</span>, <span class="st">'dcronica'</span>], </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>                             aggfunc<span class="op">=</span>{<span class="st">'n_hijos'</span>: [ <span class="st">'mean'</span>, </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>                                            (<span class="st">"casos"</span>, <span class="kw">lambda</span> x: x.count()),</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>                                            (<span class="st">"proporcion"</span>, <span class="kw">lambda</span> x: x.count()<span class="op">/</span><span class="bu">len</span>(datos))</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>                                            ]})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="conceptos-clave-de-la-regresión-lineal" class="level3">
<h3 class="anchored" data-anchor-id="conceptos-clave-de-la-regresión-lineal">Conceptos Clave de la Regresión Lineal</h3>
<p>Para entender la fórmula de la esperanza condicional de <span class="math inline">\(Y\)</span> dado <span class="math inline">\(X=x\)</span>, primero debemos comprender qué significa en el contexto de la probabilidad y la estadística. La esperanza condicional, o el valor esperado condicional, es una medida de tendencia central para una variable aleatoria (Y) dado que otra variable aleatoria (X) toma un valor específico <span class="math inline">\(x\)</span>. En el marco de la regresión lineal, la esperanza condicional nos ayuda a predecir el valor medio esperado de (Y) para un valor dado de (X), basándonos en la relación lineal entre estas dos variables.</p>
<p>La fórmula general para la esperanza condicional de (Y) dado (X=x) se expresa mediante la integral de (y) veces la función de densidad condicional de <span class="math inline">\(Y\)</span> dado <span class="math inline">\(X=x\)</span>, sobre todos los posibles valores de $y4. Matemáticamente, esto se representa como:</p>
<p><span class="math display">\[ E[Y|X=x] = \int y \cdot f_{Y|X}(y|x) \, dy \]</span></p>
<p>Donde:</p>
<ul>
<li><span class="math inline">\(E[Y|X=x]\)</span> es la esperanza condicional de (Y) dado (X=x).</li>
<li><span class="math inline">\(f_{Y|X}(y|x)\)</span> es la función de densidad de probabilidad condicional de (Y) dado (X=x).</li>
<li>La integral se calcula sobre todo el rango de posibles valores de (y).</li>
<li><strong>Regresión Lineal</strong>: Es una técnica estadística utilizada para estudiar la relación entre dos variables continuas. En este caso, estamos mirando cómo las compras (variable independiente <code>x</code>) se relacionan con las ventas (variable dependiente <code>y</code>).</li>
<li><strong>Esperanza Condicionada</strong>: Se refiere a la expectativa de una variable aleatoria dado el valor de otra. En la regresión lineal, buscamos la expectativa de <code>y</code> dado un valor específico de <code>x</code>.</li>
</ul>
<p>La regresión lineal es una herramienta poderosa para entender cómo una variable dependiente <code>y</code> está relacionada con una variable independiente <code>x</code>. Usamos una línea (la más “ajustada” posible) para describir esta relación. La ecuación general de una línea es:</p>
<p><span class="math display">\[y = \alpha + \beta x + \epsilon \]</span></p>
<p>Donde:</p>
<ul>
<li>(<span class="math inline">\(y\)</span>) es la variable dependiente (en nuestro caso, vamos a emplear las ventas de empresas de una misma industria).</li>
<li>(<span class="math inline">\(x\)</span>) es la variable independiente (en este caso, compras de las empresas).</li>
<li>(<span class="math inline">\(\alpha\)</span>) es la intersección con el eje Y o el valor de <code>y</code> cuando (x = 0). Representa el valor base de ventas sin ninguna compra.</li>
<li>(<span class="math inline">\(\beta\)</span>) es la pendiente de la línea, que indica cuánto cambia <code>y</code> por cada unidad de cambio en <code>x</code>.</li>
</ul>
</section>
<section id="estimación-de-los-coeficientes" class="level3">
<h3 class="anchored" data-anchor-id="estimación-de-los-coeficientes">Estimación de los Coeficientes</h3>
<p>La regresión lineal intenta encontrar los valores de () y () que minimizan la suma de los cuadrados de los errores (()) entre los valores observados de <code>y</code> y los valores predichos por nuestra ecuación lineal. Esto se conoce como el método de mínimos cuadrados. Las fórmulas para calcular () y () son:</p>
<p><span class="math display">\[\beta = \frac{\sum_{i=1}^{n} (x_i - \overline{x})(y_i - \overline{y})}{\sum_{i=1}^{n} (x_i - \overline{x})^2} \]</span></p>
<p><span class="math display">\[ \alpha = \overline{y} - \beta\overline{x} \]</span></p>
<p>Donde:</p>
<ul>
<li><span class="math inline">\(x_i\)</span> y <span class="math inline">\(y_i\)</span> son los valores individuales de <code>x</code> y <code>y</code>.</li>
<li><span class="math inline">\(\overline{x}\)</span> y <span class="math inline">\(\overline{y}\)</span> son los promedios de <code>x</code> y <code>y</code>, respectivamente.</li>
<li><span class="math inline">\(n\)</span> es el número total de observaciones.</li>
</ul>
<p>Es importante aclarar que (<span class="math inline">\(\alpha\)</span>) en sí mismo no es “la media” de <code>y</code>, pero sí representa el punto donde la línea de regresión cruza el eje Y, es decir, el valor esperado de <code>y</code> cuando <code>x</code> es 0. Sin embargo, si centramos nuestra atención en la ecuación de (<span class="math inline">\(\alpha\)</span>), podemos ver cómo está influenciada por los promedios de <code>x</code> y <code>y</code> a través de (<span class="math inline">\(\beta\)</span>).</p>
<p>La regresión lineal se puede entender como la estimación de la esperanza condicional de <code>y</code> dado <code>x</code>, <span class="math inline">\(E[y|x]\)</span>. Esto significa que para cualquier valor de <code>x</code>, la regresión lineal nos da el mejor pronóstico, en promedio, de <code>y</code>. En otras palabras, nos dice qué valor esperar para <code>y</code> basándonos en el valor de <code>x</code>, teniendo en cuenta la relación lineal identificada entre estas dos variables.</p>
</section>
</section>
<section id="vamos-a-ver-la-regresión-lineal-en-todo-su-poder" class="level2">
<h2 class="anchored" data-anchor-id="vamos-a-ver-la-regresión-lineal-en-todo-su-poder">Vamos a ver la regresión lineal en todo su poder:</h2>
<p>Primero, vamos a crear algunos datos “perfectos” para entender cómo funciona la regresión lineal. Ya te explicaremos por que “perfectos”.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">1984</span>) <span class="co"># Para reproducibilidad</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.random.rand(<span class="dv">100</span>) <span class="op">*</span> <span class="dv">10</span> <span class="co"># 100 puntos de compra</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>alpha <span class="op">=</span> <span class="fl">3.5</span> <span class="co"># La media</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>error <span class="op">=</span> np.random.randn(<span class="dv">100</span>) <span class="co"># Error normalmente distribuido</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> alpha <span class="op">+</span> <span class="fl">1.7</span> <span class="op">*</span> x <span class="op">+</span> error <span class="co"># Ventas simuladas</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>En este fragmento de código:</p>
<ul>
<li><code>np.random.seed(1984)</code>: Esto asegura que cada vez que ejecutes el código, los números aleatorios generados sean los mismos. Es útil para reproducibilidad.</li>
<li><code>x</code>: Representa nuestras variables independientes, en este caso, puntos de compra. Imagínalo como la cantidad de dinero gastado en publicidad.</li>
<li><code>alpha</code> y <code>error</code>: <code>alpha</code> es el término de intercepción en nuestra ecuación lineal, y <code>error</code> añade variabilidad aleatoria a nuestros datos, simulando la impredecibilidad del mundo real.</li>
<li><code>y</code>: Es nuestra variable dependiente, representando las ventas. Está calculada a partir de una relación lineal con <code>x</code> más algún error aleatorio.</li>
</ul>
<p>Ahora, ajustaremos un modelo de regresión lineal a nuestros datos simulados.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> LinearRegression()</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>resultado <span class="op">=</span> model.fit(x.reshape(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>), y) <span class="co"># Ajustar el modelo</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Aquí, <code>LinearRegression()</code> crea un nuevo modelo de regresión lineal, y <code>model.fit()</code> ajusta este modelo a nuestros datos. La parte <code>x.reshape(-1, 1)</code> simplemente reforma <code>x</code> para que tenga la forma correcta (una columna de valores en lugar de una lista plana), lo cual es necesario para el método <code>fit()</code>.</p>
<p>Vamos a ver qué tan bien nuestro modelo se ajustó a los datos.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Alpha real: </span><span class="sc">{</span>alpha<span class="sc">}</span><span class="ss">, Alpha estimado: </span><span class="sc">{</span>model<span class="sc">.</span>intercept_<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Coeficiente real: 1.7, Coeficiente estimado: </span><span class="sc">{</span>model<span class="sc">.</span>coef_[<span class="dv">0</span>]<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Esto nos mostrará el valor de <code>alpha</code> y el coeficiente que nuestro modelo estimó en comparación con los valores reales que usamos para generar los datos.</p>
<p>Finalmente, visualizamos nuestros datos simulados y la línea de regresión ajustada.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>plt.scatter(x, y, color<span class="op">=</span><span class="st">'blue'</span>, label<span class="op">=</span><span class="st">'Datos Simulados'</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>plt.plot(x, model.predict(x.reshape(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>)), color<span class="op">=</span><span class="st">'red'</span>, label<span class="op">=</span><span class="st">'Línea de Regresión'</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Compras'</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Ventas'</span>)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Esto nos da una representación visual clara de cómo la línea de regresión se ajusta a los datos simulados.</p>
<section id="supuestos-de-normalidad-en-ols" class="level4">
<h4 class="anchored" data-anchor-id="supuestos-de-normalidad-en-ols">Supuestos de Normalidad en OLS</h4>
<p>Cuando usamos Mínimos Cuadrados Ordinarios (OLS, por sus siglas en inglés) para ajustar una regresión lineal, asumimos que los errores (<code>error</code> en nuestro ejemplo) siguen una distribución normal. Esto es crucial para la inferencia estadística posterior, como calcular intervalos de confianza y realizar pruebas de hipótesis. En nuestro ejemplo simulado, respetamos este supuesto al generar <code>error</code> con <code>np.random.randn(100)</code>, que simula errores normalmente distribuidos.</p>
</section>
<section id="la-realidad-de-los-datos-en-el-mundo-real" class="level4">
<h4 class="anchored" data-anchor-id="la-realidad-de-los-datos-en-el-mundo-real">La Realidad de los Datos en el Mundo Real</h4>
<p>Aunque este ejemplo nos proporciona una comprensión clara de cómo funciona la regresión lineal, en el mundo real, los datos raramente son tan “limpios”. Los verdaderos conjuntos de datos suelen tener errores no normales, valores atípicos, y a menudo no siguen una relación lineal tan nítida. Por eso, es crucial realizar un análisis exploratorio de datos (EDA, por sus siglas en inglés) antes de ajustar cualquier modelo y considerar transformaciones de datos o modelos más complejos si es necesario.</p>
</section>
</section>
<section id="supuestos-de-la-regresión-lineal" class="level2">
<h2 class="anchored" data-anchor-id="supuestos-de-la-regresión-lineal">Supuestos de la regresión lineal</h2>
<p>Además, la regresión lineal OLS tiene una serie de supuestos que deben cumplirse para que los resultados sean válidos, incluyendo:</p>
<ul>
<li><strong>Linealidad</strong>: La relación entre las variables independientes y la variable dependiente es lineal.</li>
<li><strong>Independencia</strong>: Las observaciones son independientes entre sí.</li>
<li><strong>Homoscedasticidad</strong>: La varianza de los errores es constante a lo largo de todas las observaciones.</li>
<li><strong>Normalidad</strong>: Los errores están normalmente distribuidos.</li>
</ul>
</section>
<section id="la-regresión-lineal-como-una-prueba-de-diferencia-de-media" class="level1">
<h1>La regresión lineal como una prueba de diferencia de media</h1>
<p>Usualmente, el valor del estadístico T en los resultados de una regresión lineal OLS (Ordinary Least Squares) y el valor del estadístico T de una prueba t de dos muestras independientes (ttest_ind) no son directamente comparables, ya que se utilizan en contextos diferentes y se calculan de diferentes maneras.</p>
<ol type="1">
<li><p>En una regresión lineal OLS, el estadístico T se utiliza para probar la hipótesis nula de que un coeficiente de regresión es igual a cero (es decir, que la variable correspondiente no tiene efecto sobre la variable dependiente). Se calcula dividiendo el coeficiente de regresión por su error estándar.</p></li>
<li><p>En una prueba t de dos muestras independientes (ttest_ind), el estadístico T se utiliza para probar la hipótesis nula de que las medias de dos grupos son iguales. Se calcula como la diferencia entre las medias de los dos grupos dividida por la raíz cuadrada de la suma de las varianzas de los dos grupos dividida por sus tamaños de muestra.</p></li>
</ol>
<p>Para que los resultados de estas dos pruebas sean comparables, tendrías que estar probando exactamente la misma hipótesis en ambos casos, lo cual no es típicamente el caso. Por otro lado, la prueba t de dos muestras independientes también tiene sus propios supuestos, incluyendo la independencia de las observaciones y la igualdad de varianzas en los dos grupos (aunque hay versiones de la prueba que no requieren este último supuesto).</p>
<p>Ahora consideremos el siguiente escenario:</p>
<ol type="1">
<li>Los datos que disponemos incluye la variable <code>dcronica</code> la cual toma valores de 1 para niños con condición de desnutrición crónica infantil mientras que toma el valor de 0 cuando el niño no tiene esta condición (no siempre significa que el niño este sano, pero para el ejercicio vamos a asumir este escenario).</li>
<li>Por construcción la condición de un niño no afecta la condición de un segundo niño. Pueden compartir las mismas condiciones del hogar y la vivienda, es verdad, sin embargo vamos a considerar que estos eventos descritos en la variable <code>dcronica</code> son <strong>independientes</strong>.</li>
</ol>
<p>Debido a que este escenario cumple los mismos supuestos que la regresión lineal podemos emplear esta última como una prueba de hipótesis para la diferencia de medias. Vamos a ver como funciona.</p>
<p>Primero con la prueba T para diferencia de medias independientes:</p>
<div class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.regression.linear_model <span class="im">import</span> OLS</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Preparación de datos para una prueba de hipótesis (eliminación de NA)</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>datos <span class="op">=</span> datos[<span class="op">~</span>datos[<span class="st">"dcronica"</span>].isna()]</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>datos <span class="op">=</span> datos[<span class="op">~</span>datos[<span class="st">"n_hijos"</span>].isna()]</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Creamos los vectores:</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>desnutricion <span class="op">=</span> datos.loc[datos[<span class="st">"dcronica"</span>] <span class="op">==</span> <span class="dv">1</span>,<span class="st">"n_hijos"</span>]</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>no_desnutric <span class="op">=</span> datos.loc[datos[<span class="st">"dcronica"</span>] <span class="op">!=</span> <span class="dv">1</span>,<span class="st">"n_hijos"</span>]</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Fijate en el estadistico T del parametro estimado:</span></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>prueba <span class="op">=</span> stats.ttest_ind(desnutricion,no_desnutric,alternative<span class="op">=</span><span class="st">"greater"</span>)</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(prueba)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>TtestResult(statistic=4.210509617301763, pvalue=1.3265622420660088e-05, df=2146.0)</code></pre>
</div>
</div>
<p>Recordemos la media de los grupos:</p>
<div class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>pd.pivot_table(datos, values<span class="op">=</span><span class="st">"n_hijos"</span>, index<span class="op">=</span>[ <span class="st">"dcronica"</span>], aggfunc<span class="op">=</span>[<span class="st">"count"</span>, <span class="st">"sum"</span>, <span class="st">"mean"</span>, <span class="st">"max"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">count</th>
<th data-quarto-table-cell-role="th">sum</th>
<th data-quarto-table-cell-role="th">mean</th>
<th data-quarto-table-cell-role="th">max</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">n_hijos</th>
<th data-quarto-table-cell-role="th">n_hijos</th>
<th data-quarto-table-cell-role="th">n_hijos</th>
<th data-quarto-table-cell-role="th">n_hijos</th>
</tr>
<tr class="header">
<th data-quarto-table-cell-role="th">dcronica</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0.0</td>
<td>1740</td>
<td>3909.0</td>
<td>2.246552</td>
<td>11.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1.0</td>
<td>408</td>
<td>1038.0</td>
<td>2.544118</td>
<td>9.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Ahora con regresión:</p>
<div class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> datos[<span class="st">"dcronica"</span>]</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> datos[<span class="st">"n_hijos"</span>]</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>est <span class="op">=</span> sm.OLS(y, sm.add_constant(x))</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>est2 <span class="op">=</span> est.fit()</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(est2.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                n_hijos   R-squared:                       0.008
Model:                            OLS   Adj. R-squared:                  0.008
Method:                 Least Squares   F-statistic:                     17.73
Date:                Sun, 04 Feb 2024   Prob (F-statistic):           2.65e-05
Time:                        15:04:02   Log-Likelihood:                -3585.2
No. Observations:                2148   AIC:                             7174.
Df Residuals:                    2146   BIC:                             7186.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.2466      0.031     72.938      0.000       2.186       2.307
dcronica       0.2976      0.071      4.211      0.000       0.159       0.436
==============================================================================
Omnibus:                      629.392   Durbin-Watson:                   1.987
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1970.053
Skew:                           1.476   Prob(JB):                         0.00
Kurtosis:                       6.647   Cond. No.                         2.66
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p>Fíjate como la media del número de hijos en los hogares en los que viven los niños <em>sin desnutrición crónica</em> se presentan en el termino <code>const</code> (2.2466), mientras que el coeficiente asociado a <code>dcronica</code> es la diferencia de la media del número de hijos en los hogares en que viven los <em>niños <strong>con</strong> desnutrición crónica</em> menos la media del número de hijos en los hogares en que viven los <em>niños <strong>sin </strong> desnutrición crónica</em> (0.2976). Por último observa como el <strong>estádistico T</strong> de la prueba de diferencia de medias con <code>stats.ttest_ind</code> es el mismo que el valor <code>t</code> asociado al coeficiente <code>dcronica</code> en la tabla de regresión. (4.211)</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./clase_7.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Pruebas de hipótesis para la media entre grupos en Python</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->



</body></html>